=encoding utf8

=head1 NAME

canpi-ssr - maintain INI-type configuration files

=head1 SYNOPSIS

(B<canpi-ssr> is a web application and is controlled by I<systemd> as a service)

=head1 CONFIGURATION

The configuration file for B<canpi-ssr> is a JSON file named C<$CPSSR_HOME/canpi-ssr.json>.

=over

=item *

B<CPSSR_HOME> - Directory containing the configuration file (usually C</usr/local/etc/canpi-ssr/>)

=item *

B<HOST_PORT> - Address and port to bind the webserver to (default: C<0.0.0.0:8080>)

=item *

B<RUST_LOG> - Logging level (default: C<WARN>)

=back

=head1 SEE ALSO

L<canpi-ssr(8)>