[package]
name = "canpi-web-app-ssr"
version = "0.1.0"
authors = ["Mark Thornber <mark.thornber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5.0"
actix-rt = "1"
# Data serialisation library
serde = { version = "1", features = ["derive"] }
tera = "1.8.0"
# Other utilities
chrono = { version = "0.4", features = [ "serde" ] }
